services:

  spark-master:
    image: bitnamilegacy/spark:3.5
    container_name: person2-spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - person2-net

  spark-worker:
    image: bitnamilegacy/spark:3.5
    container_name: person2-spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    restart: unless-stopped
    networks:
      - person2-net

  processing-job:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: person2-processing-job
    depends_on:
      - spark-master
      - spark-worker
      - garage
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC: gold_stream
      GARAGE_ENDPOINT: http://garage:3900
      GARAGE_ACCESS_KEY: ${GARAGE_ACCESS_KEY}
      GARAGE_SECRET_KEY: ${GARAGE_SECRET_KEY}
      FASTAPI_URL: ${FASTAPI_URL}
      PROCESSING_INTERVAL: "10"
    restart: unless-stopped
    networks:
      - person2-net

  garage:
    image: dxflrs/garage:v2.3.0
    container_name: person2-garage
    hostname: garage
    entrypoint: /garage
    command: server
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - garage_data:/mnt/data
      - ./garage.toml:/etc/garage.toml
    restart: unless-stopped
    networks:
      - person2-net

  garage-init:
    build:
      context: .
      dockerfile: storage/garage/Dockerfile
    container_name: person2-garage-init
    depends_on:
      - garage
    environment:
      GARAGE_ENDPOINT: http://garage:3900
      GARAGE_HOST: garage
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage_data:/mnt/data
    restart: "no"
    networks:
      - person2-net

  garage-webui:
    image: khairul169/garage-webui:latest
    container_name: person2-garage-webui
    depends_on:
      - garage
    restart: unless-stopped
    ports:
      - "3909:3909"
    volumes:
      - ./garage.toml:/etc/garage.toml
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
      AUTH_USER_PASS: 'admin:$2y$10$7o8xlJPWHvdSCDXVefF5M.zUPoKI/C0l6meAwvOvdRxnRy.m5E/pC'
    networks:
      - person2-net

volumes:
  garage_data:

networks:
  person2-net:
    driver: bridge
